# Whenever you see the <state> placeholder, it will be one of these.
state:
  'on': '<yellow>on</yellow>'
  'off': '<yellow>off</yellow>'

text: '<gold>Turned</gold> <state> <gold>your FasterCrystals setting.</gold>'
